sudo: false

language: python

python:
  - '2.7'
  - '3.5'

cache:
  - pip

install:
  - pip install -r requirements.txt

script:
  - flake8 desknet
  - python setup.py test

env:
  global:
  - secure: qBONfI3LKSxDeFKo7sO8CRPfqZVv37HMuaIK6BdK0hmz9DmBFHLOovO/a9ke307PuoTJopDLvJYqnHlYyhzadhU9Cir37QnZvZKIn/jP+9TLVI9i5BLO2g8isl6at7oJBdc21nRdofmZC76hNb7iB+r+A7qsHkgDhLjPdW/8c7aKLVZ0Z//V+vRhicm3It7IyTAZG+FiOXQsONrT00Tpnmr+eK6JKfPDPlno+I9zVlTwdNZpQqxhue0zWW2W3V3Oq3C6cYXfPwmT2MwgAua4yzFxuG0u0VWR41Cz+Uz+F3ycXy7xCKIQY9tqy+2vzoGi1D7JBRu7qWTY4rfLaexXO9QToyepdb4kbKEkvgKhIluKfBy3eglhqnxZ+QDYcCyIdZ+N8UlN8ixwMWZa9GOEBrB3of0vBkcBUVb0byZUk1OW9Xg12IJdN0HaIJW3Fnf+aN3LVlE1Xfsf8g3aXjIePh5mZqyH5P+nTLSv5FMdq5sQrn2zy2u8QT7Em4DmptxfwimitIpr42uZWoMtrS+aDppJPd9NXEd/d3ArjWxmZ1SZrjWMGLscRXdEU+ewp5k5ReYYl/ul/+cpaSKWhiMdgo+vrX9wWsOqTVwyJnJGgk6hx3lMLBLCy9/EWeludp2T622qIvXYNExRsc3upPS3Its79Hj0tAtcB97D0mvQWmQ=
  - secure: uY/4VrtY9hxXWNNfIHnHf69DM1dCIw2Uof8JzlEqDa7NsgDqvqCysyiy2b8WthiTE8iFNIFd9MSDyta1ddgj0KKfe5ox8LVaRvcbcudilRxoaDSWPUxLigzLD6NLyZHnFsYptHpVHw6K23j3Z+5vV6z9GtpJRwREVjbe1GheQvMr02v3K3RnF48e9d8QVEpvypXrOPrDmWtnTEubFb7jxla/8EdffSSpRUZK10UYy4X20NDB+B8JAuwcmfY2lI/GQL6XUd04E3nRrh5sVNLIfFDPYRGTNCN6oqHMFz25WqshHWElCPZEaKFtFyNS9NZgkEn0ze/3sI+OzgVLvz9mH6iauP5Mr1FHU8ujRxJjcaqxvlekWURoRr/8d4ETuoQVbaZxovxpm+UGZB06gfAp0BhryT+kTOpkPR1eYDvcd/aRjx/I+qLdbBtLKAi2sFsCcgelp403H/SwboQIr+pfCl1oaUolyMLGFTr7xJcHRHMOH13FShOFgj1M2L1t7446aR+v3Uwd70pKs6Dq7C0dpzvjqzGUcsyzOIeJrMBacVp3jjoinotB3mTN4NzkmRoE4Rdgq2pO9uyahJmx2p2mahVQ7JfOlzt1EW3uI+Z8hisFGY9aRRdK5ZHaPbcOoWCrdDU44K0JHzJ59DGf1aSJM9OCOyZOmi6j90dEOpYiJ+Y=
